"use client";

import { useMemo, useState } from "react";
import { useSession } from "next-auth/react";
import type { MaterialDoc, SupplierDoc } from "@/lib/db";

type LinkRow = { _id: string; materialId: string; supplierId: string; leadTimeDays: number; isPrimary: boolean;
  qualificationStatus?: "APPROVED"|"CONDITIONAL"|"SUSPENDED"; sourcingRole?: "PRIMARY"|"SECONDARY";
  minLeadTimeDays?: number|null; standardLeadTimeDays?: number|null; maxLeadTimeDays?: number|null;
  currentExpectedLeadTimeDays?: number|null; currentExpectedValidUntil?: string|null; leadTimeReason?: string|null;
  emergencyOrderAllowed?: boolean; plannedSharePct?: number|null; updatedAt?: string };
type Form = { materialId:string;supplierId:string;qualificationStatus:string;sourcingRole:string;minLeadTimeDays:string;standardLeadTimeDays:string;maxLeadTimeDays:string;currentExpectedLeadTimeDays:string;currentExpectedValidUntil:string;leadTimeReason:string;emergencyOrderAllowed:boolean;plannedSharePct:string };

const emptyForm=(materials:MaterialDoc[],suppliers:SupplierDoc[]):Form=>({materialId:materials[0]?._id??"",supplierId:suppliers[0]?._id??"",qualificationStatus:"CONDITIONAL",sourcingRole:"SECONDARY",minLeadTimeDays:"",standardLeadTimeDays:"",maxLeadTimeDays:"",currentExpectedLeadTimeDays:"",currentExpectedValidUntil:"",leadTimeReason:"",emergencyOrderAllowed:false,plannedSharePct:""});
function toForm(link:LinkRow):Form{return{materialId:link.materialId,supplierId:link.supplierId,qualificationStatus:link.qualificationStatus??"CONDITIONAL",sourcingRole:link.sourcingRole??(link.isPrimary?"PRIMARY":"SECONDARY"),minLeadTimeDays:link.minLeadTimeDays?.toString()??"",standardLeadTimeDays:(link.standardLeadTimeDays??link.leadTimeDays).toString(),maxLeadTimeDays:link.maxLeadTimeDays?.toString()??"",currentExpectedLeadTimeDays:link.currentExpectedLeadTimeDays?.toString()??"",currentExpectedValidUntil:link.currentExpectedValidUntil?.slice(0,10)??"",leadTimeReason:link.leadTimeReason??"",emergencyOrderAllowed:link.emergencyOrderAllowed??false,plannedSharePct:link.plannedSharePct?.toString()??""}}

export default function ProcurementMasterClient({initialMaterials,initialSuppliers,initialLinks}:{initialMaterials:MaterialDoc[];initialSuppliers:SupplierDoc[];initialLinks:LinkRow[]}){
  const {data:session}=useSession(); const role=(session?.user as {role?:string})?.role; const canEdit=role==="ADMIN"||role==="MATERIALS";
  const [links,setLinks]=useState(initialLinks); const [selectedId,setSelectedId]=useState<string|null>(null); const [form,setForm]=useState<Form>(()=>emptyForm(initialMaterials,initialSuppliers)); const [message,setMessage]=useState(""); const [filter,setFilter]=useState("");
  const materialMap=useMemo(()=>new Map(initialMaterials.map(item=>[item._id,item])),[initialMaterials]); const supplierMap=useMemo(()=>new Map(initialSuppliers.map(item=>[item._id,item])),[initialSuppliers]);
  const covered=new Set(links.map(link=>link.materialId)); const approved=new Set(links.filter(link=>link.qualificationStatus==="APPROVED").map(link=>link.materialId)); const ranged=new Set(links.filter(link=>link.minLeadTimeDays!=null&&link.maxLeadTimeDays!=null).map(link=>link.materialId));
  const visible=links.filter(link=>{const material=materialMap.get(link.materialId);const supplier=supplierMap.get(link.supplierId);return `${material?.code} ${material?.name} ${supplier?.name}`.toLowerCase().includes(filter.toLowerCase())});
  async function refresh(){const response=await fetch("/api/material-suppliers");if(response.ok){const data=await response.json();setLinks(data.links.map((link:LinkRow)=>({...link,currentExpectedValidUntil:link.currentExpectedValidUntil?String(link.currentExpectedValidUntil):null})))}}
  async function save(){setMessage("");const url=selectedId?`/api/material-suppliers/${selectedId}`:"/api/material-suppliers";const response=await fetch(url,{method:selectedId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json();if(!response.ok){setMessage(data.error??"저장 실패");return}await refresh();setSelectedId(null);setForm(emptyForm(initialMaterials,initialSuppliers));setMessage("저장했습니다.")}
  async function remove(){if(!selectedId)return;const response=await fetch(`/api/material-suppliers/${selectedId}`,{method:"DELETE"});if(response.ok){await refresh();setSelectedId(null);setForm(emptyForm(initialMaterials,initialSuppliers));setMessage("삭제했습니다.")}}
  const field=(key:keyof Form,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  return <div><div className="mb-5 flex items-end justify-between"><div><h1 className="text-2xl font-extrabold">조달 기준 관리</h1><p className="mt-1 text-sm text-[#888]">승인 공급사와 리드타임 근거를 관리하고 운영 What-if에 연결합니다.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-[11px] font-bold text-blue-700">PROCUREMENT MASTER</span></div>
    <div className="mb-5 grid grid-cols-4 gap-3">{[["전체 자재",initialMaterials.length],["공급사 연결",covered.size],["승인 공급사 보유",approved.size],["리드타임 범위 완료",ranged.size]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-4"><div className="text-[11px] text-[#888]">{label}</div><div className="mt-2 text-2xl font-extrabold">{value}<span className="ml-1 text-xs font-normal text-[#999]">종</span></div></div>)}</div>
    <div className="grid grid-cols-[1fr_420px] gap-5"><section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-4"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="자재·공급사 검색" className="w-72 rounded-xl border px-3 py-2 text-sm"/><button disabled={!canEdit} onClick={()=>{setSelectedId(null);setForm(emptyForm(initialMaterials,initialSuppliers))}} className="rounded-xl bg-[#0078D4] px-3 py-2 text-xs font-bold text-white disabled:opacity-40">+ 신규 연결</button></div><div className="max-h-[650px] overflow-auto"><table className="w-full text-xs"><thead className="sticky top-0 bg-[#F8F6F4]"><tr>{["자재","공급사","상태·역할","리드타임","범위","긴급"].map(h=><th key={h} className="px-4 py-3 text-left text-[#777]">{h}</th>)}</tr></thead><tbody>{visible.map(link=>{const material=materialMap.get(link.materialId);const supplier=supplierMap.get(link.supplierId);return <tr key={link._id} onClick={()=>{setSelectedId(link._id);setForm(toForm(link));setMessage("")}} className={`cursor-pointer border-t hover:bg-blue-50/40 ${selectedId===link._id?"bg-blue-50":""}`}><td className="px-4 py-3"><b>{material?.code}</b><div className="text-[10px] text-[#888]">{material?.name}</div></td><td className="px-4 py-3">{supplier?.name}</td><td className="px-4 py-3"><b>{link.qualificationStatus??"미이관"}</b><div className="text-[10px] text-[#888]">{link.sourcingRole??(link.isPrimary?"PRIMARY":"SECONDARY")}</div></td><td className="px-4 py-3 font-bold">{link.standardLeadTimeDays??link.leadTimeDays}일</td><td className="px-4 py-3">{link.minLeadTimeDays!=null&&link.maxLeadTimeDays!=null?`${link.minLeadTimeDays}~${link.maxLeadTimeDays}일`:<span className="text-amber-700">미등록</span>}</td><td className="px-4 py-3">{link.emergencyOrderAllowed?"가능":"-"}</td></tr>})}</tbody></table></div></section>
      <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-extrabold">{selectedId?"조달 기준 수정":"공급사 연결 등록"}</h2>{!canEdit&&<span className="text-[10px] text-amber-700">조회 전용</span>}</div><div className="mt-4 grid grid-cols-2 gap-3">
        <label className="col-span-2 text-xs font-bold">자재<select disabled={!!selectedId||!canEdit} value={form.materialId} onChange={e=>field("materialId",e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal">{initialMaterials.map(item=><option key={item._id} value={item._id}>{item.code} · {item.name}</option>)}</select></label><label className="col-span-2 text-xs font-bold">공급사<select disabled={!!selectedId||!canEdit} value={form.supplierId} onChange={e=>field("supplierId",e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal">{initialSuppliers.map(item=><option key={item._id} value={item._id}>{item.name}</option>)}</select></label>
        <label className="text-xs font-bold">승인 상태<select disabled={!canEdit} value={form.qualificationStatus} onChange={e=>field("qualificationStatus",e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal"><option>APPROVED</option><option>CONDITIONAL</option><option>SUSPENDED</option></select></label><label className="text-xs font-bold">조달 역할<select disabled={!canEdit} value={form.sourcingRole} onChange={e=>field("sourcingRole",e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal"><option>PRIMARY</option><option>SECONDARY</option></select></label>
        {[["최소 리드타임","minLeadTimeDays"],["기준 리드타임 *","standardLeadTimeDays"],["최대 리드타임","maxLeadTimeDays"],["현재 예상","currentExpectedLeadTimeDays"]].map(([label,key])=><label key={key} className="text-xs font-bold">{label}<input disabled={!canEdit} type="number" min="0" value={form[key as keyof Form] as string} onChange={e=>field(key as keyof Form,e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal"/></label>)}
        <label className="text-xs font-bold">현재값 유효기간<input disabled={!canEdit} type="date" value={form.currentExpectedValidUntil} onChange={e=>field("currentExpectedValidUntil",e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal"/></label><label className="text-xs font-bold">계획 배정(참고)<input disabled={!canEdit} type="number" min="0" max="100" value={form.plannedSharePct} onChange={e=>field("plannedSharePct",e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal"/></label>
        <label className="col-span-2 text-xs font-bold">현재 예상 변경 사유<input disabled={!canEdit} value={form.leadTimeReason} onChange={e=>field("leadTimeReason",e.target.value)} className="mt-1 w-full rounded-lg border px-2 py-2 font-normal"/></label><label className="col-span-2 flex items-center gap-2 text-xs font-bold"><input disabled={!canEdit} type="checkbox" checked={form.emergencyOrderAllowed} onChange={e=>field("emergencyOrderAllowed",e.target.checked)}/> 긴급 발주 가능</label>
      </div>{message&&<div className={`mt-3 rounded-lg p-2 text-xs ${message.includes("했습니다")?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{message}</div>}<div className="mt-5 flex gap-2"><button disabled={!canEdit} onClick={()=>void save()} className="flex-1 rounded-xl bg-[#0078D4] py-2.5 text-xs font-bold text-white disabled:opacity-40">저장</button>{selectedId&&<button disabled={!canEdit} onClick={()=>void remove()} className="rounded-xl border border-red-200 px-4 text-xs font-bold text-red-600 disabled:opacity-40">삭제</button>}</div><div className="mt-4 rounded-xl bg-[#F8F6F4] p-3 text-[11px] leading-5 text-[#666]">최소·최대값은 임의 추정하지 않습니다. 범위가 없으면 What-if에서 안전 발주일을 계산하지 않습니다. 계획 배정 비율은 참고 정보이며 자동 분할에 사용하지 않습니다.</div></section></div>
  </div>
}
