const LOGS = [
  { day: 0, date: "2026-07-08", label: "환경 세팅", color: "#F7A600", items: ["Prisma 7 및 SQLite 어댑터 구성", "Next.js 16 proxy 규칙 적용", "라이트 테마 고정과 기본 UI 토대 구성"] },
  { day: 1, date: "2026-07-10", label: "핵심 운영 화면", color: "#EA002C", items: ["종합 현황과 AI 브리핑", "재고·DOH 및 공정별 사용량 화면", "업무 일지와 개발 이력 탭"] },
  { day: 2, date: "2026-07-11", label: "인증 정상화와 MongoDB 이전", color: "#00B96B", items: ["배포 환경변수 오류 진단 및 인증 수정", "Turso·Prisma에서 MongoDB Atlas 네이티브 드라이버로 이전", "공정·창고 3D 연결과 카메라 포커스 구현"] },
  { day: 3, date: "2026-07-12", label: "단일 진실원과 데이터 정합", color: "#0078D4", items: ["ProcessUsage를 일사용량·월소요량·DOH의 기준으로 통합", "현장생산 자재와 fallback 계산 규칙 정리", "크리·패브·엑스 3인 기획팀 체계 도입"] },
  { day: 4, date: "2026-07-12", label: "FAB 규모와 3D 현실화", color: "#7C3AED", items: ["재고·공정소비량을 FAB 운영 규모로 확장", "3D 레이아웃과 창고 Capacity 정합성 강화", "수요 변화 시나리오의 공정·창고 영향 연결"] },
  { day: 5, date: "2026-07-14", label: "MES Phase 1", color: "#0891B2", items: ["BOM 기반 작업지시와 상태 전이", "FEFO Lot 피킹과 권한 검증", "공정 준비도·사용량·MES 양방향 연결"] },
  { day: 6, date: "2026-07-15", label: "운영 데이터 통합과 자재 허브", color: "#0F766E", items: [
    "재고·Lot·MES 작업지시 변경을 트랜잭션과 서버 권한 검증으로 강화",
    "랜덤 공급 시뮬레이션을 제거하고 복수 제품 증·감산 기반 결정론적 What-if로 개편",
    "승인 공급사, 주·보조 역할, 최소·기준·최대·현재 리드타임을 관리하는 조달 기준 마스터 구축",
    "What-if에 일반·안전 발주 마감일과 대체 공급사 정보를 연결",
    "재고 목록의 자재를 재고·창고·Lot·공정 사용량·BOM·조달 리드타임 종합 운영 허브로 연결",
    "자재 ID를 공통 식별자로 통일하고 중복 재고·사용량 합산 및 Lot 집계 범위를 교정",
    "대시보드 메뉴와 오래된 시뮬레이션 코드·문서를 현행 운영 목표에 맞게 정리",
    "프로덕션 빌드와 전체 E2E 20개 시나리오 통과",
  ] },
  { day: 7, date: "2026-07-16", label: "1WMS / 3FAB Control Tower 재설계", color: "#2563EB", items: [
    "상단 중앙 WMS와 하단 M20·M21·M22를 연결하는 ㅗ형 공정 흐름도 구축",
    "WMS 가용재고를 3개 FAB의 합산 일사용량으로 나누는 SKU별 통합 잔여일 계산 적용",
    "CAMPUS와 FAB별 선택에 따라 기준 SKU·배분재고·일사용량·경보·오늘의 조치가 전환되도록 연결",
    "품질보류·격리 재고를 가용재고에서 제외하고 서로 다른 자재와 단위를 합산하지 않는 계산 규칙 반영",
    "각 FAB의 일사용량·수요 비중·공용재 배분 예정량·예상 잔여일을 WMS 흐름과 함께 표시",
    "기존 3D 공정 화면은 보존했으며 Control Tower 선택 상태와 3D 화면의 직접 연동은 후속 범위로 분리",
    "계산 규칙 테스트, TypeScript, ESLint, 브라우저 렌더링 및 Webpack 프로덕션 빌드 검증 완료",
  ] },
  { day: 8, date: "2026-07-17", label: "WMS–3FAB Campus Material Twin 1차", color: "#0F766E", items: [
    "1WMS 상단과 M20·M21·M22 하단을 ㅗ형 동선으로 묶은 Campus 전체 3D 허브 구축",
    "자재·Fab·시설·Lot·Handling Unit·Flow Step·카메라 선택 상태를 URL과 공통 Context로 유지",
    "Campus에 전체 물리 창고를 항상 표시하고 선택 SKU의 실제 보관창고→수요 Fab 경로만 강조",
    "기존 공정별 사용량의 P01~P10 장비·AMHS·FOUP·자재 배관은 분석용 독립 탭으로 유지하면서 Twin Fab 상세에도 재사용",
    "M20 HBM TSV·적층본딩, M21 DRAM 셀·배선 어레이, M22 3D NAND HAR 식각·Stack CVD로 장비 밀도와 대표 설비 구성을 분리",
    "Fab 투명 외벽·지붕과 공중 계획 노드를 제거하고 Fab 식별 라벨을 바닥 전면으로 이동",
    "실제 TransferOrder가 CREATED·PICKING·STAGED·IN_TRANSIT·RECEIVED일 때만 물류 캐리어를 표시하고, 전체 활성 자재를 동시에 렌더링",
    "TransferOrder가 없는 창고 물류는 정지시키고 ETA 예상 위치·15초 이내 실측 위치·지연 상태를 구분해 표시하며 도착 후 재순환 애니메이션 제거",
    "M20 대표 수직 경로를 WMS 재고→Allocation→피킹→Staging→이송→PRS→Line-side→MES 소비로 분리",
    "MES 작업지시 생성 시 Fab별 Allocation·TransferOrder·Flow Event를 동시 생성하고 Lot 피킹 시 실제 창고·위치·Lot·Handling Unit을 같은 이송에 결합",
    "5초 Transfer Feed, 순방향 상태 전이 API, IN_TRANSIT 실측 좌표 수신 API를 추가하고 완료·취소 주문은 활성 3D 장면에서 제거",
    "Campus에서 창고 코드·실제 명칭·Capacity를 일치시키고 다른 SKU로 진입해도 창고 상세 전체 위치가 비어 보이지 않도록 필터 규칙 수정",
    "M20 P10 HBM 대표 작업지시를 PKG-001 98kg·Lot 1개·HU 1개로 생성하고 FEFO 예약→출고→이송→PRS→Line-side→소비까지 실제 Mongo 원장으로 완주",
    "피킹 시 Lot 가용량만 예약하고 IN_TRANSIT 출발 때 WMS 재고를 차감해 이중 차감을 제거했으며, PRS·Line-side·소비 수량 보존과 requestId 멱등 이벤트를 적용",
    "M20 공정별 Equipment Master 452대를 모델링 기준으로 구축하고 가동 장비의 rated capacity×OEE를 장비 Capacity와 3D 장비 밀도에 연결",
    "공정별 사용량 화면에 기존 월 기준소요량과 CONSUMED 이벤트 기반 최근 30일 실제 사용량을 분리 표시",
    "실제 원장 단계와 아직 미연결된 계획 단계를 초록·노랑으로 명확히 구분해 가상 이송을 LIVE로 오인하지 않도록 설계",
    "Facility·Allocation·TransferOrder·Flow Event 인덱스와 기존 WorkOrder fabId 보정을 포함한 안전한 DB 초기화 스크립트 추가",
    "동시 이송·실측 우선·ETA 정지·역전이 및 재순환 금지 규칙 테스트와 TypeScript·ESLint·브라우저·Webpack 빌드 검증 완료",
  ] },
  { day: 9, date: "2026-07-17", label: "M20 규칙형 운영 에이전트 1차", color: "#6332A8", items: [
    "자유 판단형 LLM 대신 동일 입력에 동일 결정을 내리는 발주·WMS·MES·공정 규칙형 에이전트 구축",
    "AgentRun·AgentDecision 원장에 정책 버전, 입력 스냅샷, 사유 코드, 실행 결과와 멱등키 기록",
    "PKG-001의 3FAB 합산 일사용량·안전재고·21일 리드타임·가용재고·예약·확정입고를 반영한 보충 발주량 계산",
    "하드코딩 모델 공급사·MOQ·주문배수·기준가격으로 운영 PO 초안을 생성하고 사람 승인 전 외부 Outbox 생성을 차단",
    "WMS 에이전트의 FEFO Lot/HU 논리 예약과 현장 피킹 완료 확인을 분리해 물리 실적 자동 생성 방지",
    "Line-side 도착 후 MES가 자재와 모델 Capacity를 검증하고 공정 에이전트가 M20 P10 장비를 중복 없이 예약한 뒤 WO Release",
    "출발·도착·인계·소비는 기존 권한 기반 물리 확인 API만 허용하고 각 확인 뒤 에이전트가 다음 단계 자동 조율",
    "M20 대표 흐름 화면에 4개 에이전트 결정, 차단 사유, PO 계산 근거·승인·Outbox, 모델 장비 배정을 통합 표시",
  ] },
  { day: 10, date: "2026-07-17", label: "Campus 전체 자재·Scene Clock", color: "#1D5FBF", items: [
    "LIVE CAMPUS MATERIAL SCENE 자재 범위의 기본값을 전체 자재로 변경하고 URL material 파라미터가 없으면 이전 선택을 초기화",
    "전체 자재에서는 단위가 다른 수량을 합산하지 않고 자재종·활성 Transfer·이동 중 HU·출발 창고 기준으로 집계",
    "개별 자재 선택 시 Transfer 목록과 3D 장면을 동일 SKU 조건으로 필터링하고 기존 상세 원장·공정 Trace를 유지",
    "서버 응답 시각과 브라우저 수신 시각의 오프셋을 계산하는 SceneClock을 도입해 목록 진행률과 3D 위치의 기준 시각 통일",
    "LIVE·일시정지·현재로 복귀 조작을 추가하고 PAUSED 상태에서 Transfer 폴링·Scene 프레임·운영 드릴다운 정지",
    "전체 모드에서 IN_TRANSIT만 HU 단위로 이동시키고 CREATED·PICKING·STAGED·RECEIVED는 시설·상태별 정지 표식으로 집계",
    "OS·MongoDB 시간과 실제 이벤트 원장은 변경하지 않으며 과거 재생·배속은 시점 Projection 원장 구축 전까지 차단",
    "Control Tower=조치, Digital Twin=물리 위치·이송, 공정별 사용량=계획·실사용·차이 분석으로 역할 분리",
    "Campus WebGL 컨텍스트 유실 시 3D 자동 재생성과 WMS·3FAB 운영 장면 fallback을 적용해 흰 화면 고착 방지",
    "공정별 사용량 메뉴에서 학습 문구를 제거하고 Fab 범위를 M20→M21→M22→전체 3FAB 순서로 통일",
    "전체 비교에서는 서로 다른 자재 단위를 합산하지 않고 Fab별 자재·공정·계획·30일 실적·장비 원장 연결 건수 표시",
    "Fab 선택 시 자재별 계획 일사용량과 최근 30일 평균 실사용량, 적용 공정, 장비 Capacity와 Fab 3D를 함께 조회",
    "M20=HBM, M21=DRAM, M22=NAND를 운영 매핑으로 명시하고 제품은 Fab의 하위 속성으로 정리",
    "P01~P10 공정 사전에 한영 명칭·목적·전후 공정·설비·자재·KPI·산출물과 MODELED_BASELINE 정합성 안내 추가",
    "M20 실제 수직 원장을 기준 모델로 집중 완성한 뒤 공통 엔진으로 M21·M22를 확장하는 전략 확정",
  ] },
  { day: 11, date: "2026-07-18", label: "실제 공정 라우트 + 12-FOUP 실시간 추적", color: "#0EA5E9", items: [
    "일일 생산 실적 원장(productionActuals)을 추가해 일일 통제 화면의 재고·DOH 투영을 계획치 대신 확정 실적 기준으로 계산",
    "materialReroute로 자재 전용 경로 변경을 기록하고, MES 공정 준비도·자재 상세·로그인 화면에 남아있던 이천 M14/M16 표기를 M20/M21/M22 기준으로 정리",
    "Applied Materials·SK하이닉스 뉴스룸·Samsung Newsroom·imec·SemiEngineering 등 업계 공개 자료를 근거로 HBM·DRAM·NAND 실제 공정 흐름을 문서화(docs/route-master.md)하고 routeMaster 컬렉션으로 시딩",
    "waferLots·waferLotStepEvents 실행 원장을 추가해 FOUP-01 하나만 되던 3D 실시간 추적을 FOUP-01~12 전부로 확장",
    "FOUP가 130스텝 라우팅을 완주하면 새 웨이퍼 25장 로트로 자동 재적재되는 순환 구조 구현",
    "패키징 노드 첫 진입 시 M20 파일럿 워크오더를 자동 생성해 WMS 예약·소비·발주 에이전트 체인을 재트리거 — 재고가 계속 깎이기만 하고 발주로 이어지지 않던 문제 해소",
    "6초 폴링마다 MES_TELEMETRY 트리거로 1스텝씩 자동 진행하는 타이머를 추가하고 기존 OPERATOR_CONFIRM 수동 확인 버튼과 병행",
    "docs/vision.md에 시뮬레이션 배속(약 1.2만~1.6만배, 균등 배분 가정)을 기록하고 '타임 액셀러레이터 제외' 원칙이 Phase 4 What-if 트윈에 한정됨을 명시",
    "실 DB 시나리오 스크립트(test:wafer-lot-12foup)로 FOUP 독립성·패키징 트리거·재적재 순환을 검증하고 TypeScript·ESLint·브라우저 콘솔 0 에러 확인",
  ] },
  { day: 12, date: "2026-07-19", label: "M20 생산능력·설비·FOUP 실행 원장 통합", color: "#EA002C", items: [
    "M20 NORMAL 생산능력을 117,000 WSPM으로 확정하고 HBM4 12-Hi 36GB 기준 월 5,703,750개 계획 생산량과 wafer당 KGD·stack 수율 계산 계약 수립",
    "M21·M22는 미정으로 분리하고 fab-master·route-master·material-consumption-master를 가정·신뢰도·변경관리 기준이 있는 단일 문서 체계로 정리",
    "P10 Packaging 안에 Dicing·Die Sort·Base Die Attach·12단 DRAM Bonding·MUF·Final Test를 통합하고 외부 조달 Base Die KGD와 후공정 자재·BOM 연결",
    "M20 117K WSPM을 업계형 여유율로 감당하도록 공정별 Equipment Master를 494대로 확정하고 장비 Capacity·OEE·가동률·병목 여유를 화면과 API에 연결",
    "3D에 494대 설비를 대표 샘플이 아닌 전수 instance로 반영하고 P09 Test와 P10 Packaging을 하나의 후공정 라인으로 연결해 OHT·AGV 동선을 단축",
    "Little's Law 기준 일 156 Lot, Wafer/FOUP 체류 90일, Occupied 14,040대, Physical FOUP Fleet 15,600대, Reserve 1,560대 실행 계약 수립",
    "M20:HBM:V3 Route에 14,040개 활성 Wafer Lot·15,600개 FOUP·14,040개 활성 Assignment를 멱등 bootstrap하고 기존 Aggregate WIP 20,828개는 완료 이력으로 보존",
    "전체 Lot 실행 원장 API와 검색·10개 단위 페이지 조회를 추가해 Modeled 14,028개와 Watched 12개를 동일 화면에서 Lot·FOUP·공정·Carrier 기준으로 추적",
    "3D는 설비와 겹치는 압축 FOUP density를 제거하고 이동 의미가 있는 Watched 12개만 표시하며 전체 수량은 LEDGER_EXACT 원장과 수량판을 기준으로 분리",
    "실행추적의 전체 원장 선택과 Watched 상세 선택을 하나로 통합해 서로 다른 FOUP 정보가 동시에 표시되던 이중 선택 UX 제거",
    "FOUP bootstrap 재실행 추가 생성 0건, 14,040 Lot/Assignment 불변식, 494대 3D, 생산 시나리오, TypeScript, ESLint 및 Next.js 프로덕션 빌드 검증 완료",
  ] },
  { day: 13, date: "2026-07-21", label: "M21·M22 Fab Master 정의 + 로그인 역할 선택", color: "#DB2777", items: [
    "로그인 폼을 아이디/비밀번호 입력에서 역할 선택 타일로 교체하고 헤더에 역할 스위처를 추가",
    "M20 공정별 사용량 3D에 노드 밀도 카드와 실시간 가동률 미리보기를 추가하고, 만 단위가 넘는 FOUP 표현·슬라이더 UX를 개선",
    "M21(DRAM)·M22(NAND)를 M20과 동일한 문서 rigor로 fab-master·route-master·material-consumption-master·fab-equipment-master 5개 마스터 문서에 정의 — M20 숫자를 복사하지 않고 공개 업계 자료(Applied Materials·SK hynix Newsroom·imec·SemiEngineering·Lam Research)로 독립 도출",
    "M21·M22의 WSPM을 최초 추정치(80K/100K)에서 실제 SK hynix 팹급 벤치마크로 재산정 — M21 184,000 WSPM(M16급 1c DRAM 17만~19만 실측 근거), M22 108,000 WSPM(NAND 단일 라인 10만~12만 실측 근거) — 하위 설비·자재·시나리오 전체 재계산",
  ] },
  { day: 14, date: "2026-07-22", label: "M21·M22 실DB 동기화 + 3D 레이아웃 재설계 + 설비 대수 일관화", color: "#4F46E5", items: [
    "M21·M22의 routeMaster·equipmentMaster·materialConsumption을 문서 승인 단계에서 실제 MongoDB 원장으로 동기화 — M20과 동일한 구현 깊이로 마이그레이션 스크립트 4종 추가",
    "M20 전용이던 장비 카드를 FabEquipmentMasterView 기반 3-fab 공용 카드로 일반화하고, 대수 0인 공정을 목업으로 채우지 않고 실제로 숨기도록 수정",
    "M21·M22 3D 트윈에서 대수 0인 P08이 4대로 표시되던 phantom 렌더링 버그와, 공정당 대수가 크게 다른 fab에서 설비가 바닥 밖으로 넘치던 버그를 원장 기반 bay 단위 bin-packing으로 해결",
    "OverheadInfra·AgvLogisticsInfra·가스야드 배관이 여전히 M20 시대 고정 좌표를 쓰던 버그와, 바닥·타일 그리드가 실제 zone 중심과 2.25만큼 어긋나 있던 FAB_CENTER_Z 버그를 수정하고 첫 공정 앞 빈 통로에 gowning/에어샤워 게이트를 배치",
    "설비 대수 산정을 병목/비병목 목표 부하 기준(병목 85%, 비병목 75%)으로 3팹에 일관 적용 — M20은 기존 설치 대수 하한을 없애 494→329대로, M21·M22는 병목이 아닌 공정에 여유를 둬 488→495대·512→533대로 재계산",
    "M20 equipmentMaster 초과분 165대를 equipmentAssignments 미참조 확인 후 스냅샷을 남기고 안전하게 삭제하는 일회성 trim 스크립트로 반영",
    "공정 카드 레이아웃에서 공정명이 길 때 대수·단위가 두 줄로 줄바꿈되던 버그 수정, TypeScript·ESLint·브라우저 3-fab 렌더링 검증 완료",
    "M21·M22 P10(컨벤셔널 패키징)의 계획 부하 N/A를 해소 — Backgrind·Dicing은 M20과 동일 가정, Final Test는 CS MANTECH 2018 공개 문헌 기준 UPH, 나머지 4단계는 업계 통상 처리량 범위로 7-stage capacity 모델을 신설(INDUSTRY_RANGE_INFORMED_MODELED_BASELINE 명시)",
    "M21 P10 57→434대(내부 병목 Molding 84.7%), M22 P10 33→139대(내부 병목 Wire Bond 84.9%)로 재계산하고 기존 추가 전용 마이그레이션 스크립트로 DB 반영",
  ] },
  { day: 15, date: "2026-07-25", label: "Twin Physics Engine + 재고 프로비저닝 진단 + 화면 컴팩트화", color: "#0D9488", items: [
    "각 공정이 실시간으로 창고 재고를 소모하고 ROP 미달 시 자동 발주→리드타임 후 입고로 되채우는 서버 주도 양방향 Twin Physics Engine 구축 — instrumentation 훅이 5초 setInterval로 매 tick WIP 진행→자재별 창고재고 배치 차감→PO 발주·입고 정산 실행(신규 컬렉션 twinEngineState·twinPurchaseOrders·twinBurnEvents, InventoryDoc.avgDailyBurn)",
    "소모 계산·입고 계획·EMA를 순수 함수로 분리하고 DB 오케스트레이션(executeTwinTick)은 락으로 tick 상호배제, 소모는 AGGREGATE 코호트만 반영해 VISUAL 파일럿 배관과 이중 차감 없이 무회귀 — 10개 태스크 subagent-driven TDD + 태스크별·최종 whole-branch 리뷰(GET force-dynamic Critical 1건 수정) 후 main 병합",
    "\"consume에 재고 미반영 버그\"로 출발했으나 자재 흐름 추적 결과 창고 inventory는 출고(IN_TRANSIT) 시점에 이미 차감됨을 확인 — decrease 추가 시 이중 차감이라 수정하지 않고, 진짜 gap은 AGGREGATE 생산 물량이 자재를 아예 안 태우던 것으로 규명",
    "가용 재고 부족 근본 원인 진단: 소비 마스터가 117K WSPM으로 상향된 뒤 오프닝 재고 프로비저닝이 현재 스케일로 적용된 적이 없어 41/44 자재가 ROP 미만 — 벌크 가스(N₂ 등)가 실린더(봄베)로 잘못 모델링돼 재고를 채우면 창고 capacity가 폭발하니 억지로 작게 눌러온 구조임을 warehouse-capacity-master 기준과 대조해 확인",
    "엔진 캘리브레이션 수정 — avgDailyBurn을 실벽시계(5초)로 정규화하던 것을 SIM_DAYS_PER_TICK(사이클타임/스텝수≈0.808일)로 교체해 ~1.7만배 왜곡 제거, ProcessUsage 기준 daily-control과 정합(순수+통합 테스트 검증)",
    "트윈 엔진이 실제 생산 WIP를 소모하지 못하던 코호트 이름 불일치 버그 발견 — 실 가동 WIP는 cohort=MODELED_FOUP(14,028개)인데 advanceAggregateWip은 cohort=AGGREGATE만 진행하고 있었음(후속 수정 대상으로 기록)",
    "무거워진 시스템 정리 — 참조·네비 링크 없는 고아 화면(/risk·/wiki)과 스텁 화면(/value·/scm route)을 제거하고 재사용 컴포넌트(ProcurementMasterClient)는 유지, 실시간 연동 통합 Control Tower 뷰(심박 스트립·Runway·탱크 액위 게이지) 설계 확정",
  ] },
  { day: 16, date: "2026-07-26", label: "입고 에이전트 그림자 조종석 + 에이전트 문서 체계 착수", color: "#CA8A04", items: [
    "전날 미완이던 시장·수요 라이브 연동(TWSE/SEC)·자재/운영 What-if 코파일럿을 브라우저 실검증(TWSE FRESH 실매출·SEC DISABLED 폴백·AI 39자재 추천·PATCH 확인 왕복) 후 병합 — LOGISTICS 계정에 노출되던 날것 'Forbidden' 문구를 권한 안내 문구로 교체",
    "'오늘의 입고 실적'을 신규 페이지로 만들었다가 WMS 입출고 이력과 정보구조상 중복된다는 지적을 받아 WMS 서브탭([오늘 입고 실적|입출고 이력|재고 Lot])으로 재통합 — 입고 등록 버튼을 1개로 단일화하고 히어로 펄스(건수·카테고리별 단위 총량·건수기반 계획 달성률·시간대 스파크라인)와 계획 vs 실입고 레이스 트랙은 유지",
    "입고(PROCUREMENT) 에이전트 MVP-0 '그림자 조종석' 구축 — 크리·패브·엑스 3인 기획 검토(위험물·단일소싱 자재 L2 자동입고 상한 하드가드, 리드타임·공급사 미등록 시 BLOCKED, 실측 리드타임 원장 없이는 자동 승급·강등 보류) 반영, 결정론 엔진 결과를 4단계 추론 사슬(생산계획 신호→부족 예측→리드타임 커버리지→발주 판단)로 서술화, 실제 발주·입고 실행은 0건(그림자모드) — 실데이터로 조치대상 59·제안 31·보류 28 렌더 검증",
    "입고 관제 화면에서 CSM-016~019(Edge Trim Blade·Dicing Blade·Dicing UV Tape·KGD Die Tray)가 정보 없이 비는 원인 진단 — RATE_TBD 미보정 스텁이라 원단위·재고·공급사가 전부 비어있었음을 확인, 계획 가정치(CSM_BACKEND_PLANNING_V0)로 원단위·공급사(Disco·Peak International)·재고 포지션을 idempotent 마이그레이션으로 채움",
    "docs/agents/ 폴더 신설, PROCUREMENT 에이전트 정식 설계 문서(procurement-master.md) 작성 — 레거시 M20 파일럿 에이전트(WO 트리거·agentDecisions 영속)와 신규 그림자 에이전트(화면 트리거·미영속)가 서로 다른 두 시스템임을 명시하고, '그림자모드는 MVP-0 시작점이지 종착점이 아니다'로 경계를 MVP 임시제약과 다른 에이전트 역할분담으로 재구성 — 이 틀로 WMS·MES·PROCESS 에이전트 문서를 다음 세션에서 이어 작성 예정",
  ] },
  { day: 17, date: "2026-07-28", label: "관제탑 라이브 4인 OpenAI 자동 판단", color: "#7C3AED", items: [
    "별도 회의실 없이 기존 Control Tower Live에 김구매·이자재·최생산·박물류 4인의 판단과 대화 기록을 통합",
    "김구매는 기존 결정론적 발주 판단을 LLM이 설명하는 RULE_LLM, 나머지 3인은 향후 규칙 엔진을 교체 연결할 수 있는 LLM_ONLY 모드로 구현",
    "버튼 없이 Twin의 의미 있는 상태 변화에 4인 독립 판단→최대 2건의 담당자 답변→관제 결론을 자동 생성하고, 단순 수량 변화·화면 폴링에는 중복 호출하지 않도록 의미 스냅샷을 정규화",
    "OpenAI Responses API Structured Outputs·근거 참조 검증·store:false·도구 미제공을 적용해 운영 원장을 변경하지 않는 읽기 전용 자문으로 제한",
    "MongoDB 에피소드에 실행 lease·상태 중복 제거·재시도 간격·토큰 사용량을 기록하고 UI에 모델·연결 상태·4인 발언·질의응답·결론·오류를 표시",
    "TypeScript·ESLint·Next.js production build·Playwright E2E 통과, 자동 스케줄러 호출 및 동일 상태 1회 실행 검증 — API 키 인증은 성공했으나 계정 크레딧 부족(insufficient_quota)으로 실제 답변 생성은 결제 후 활성화 예정",
  ] },
  { day: 18, date: "2026-08-02", label: "4인 실판단 가동 + Twin 처리량·재고 안정화", color: "#059669", items: [
    "OpenAI 크레딧 충전 후 gpt-5.6·gpt-5.6-luna 실호출 검증하고 CONTROL_TOWER_AI_MODEL 기본값을 luna로 전환 — 관제탑 4인 자동 판단 최초 가동 확인",
    "Twin이 5일째 'RUNNING'으로 보이지만 실제로는 burn·PO가 완전히 멈춰있던 버그 규명 — MODELED_FOUP 14,040개가 2026-07-19 bootstrap 이후 07-28에 전량 DONE 소진, 재투입 로직 부재가 원인이었음. releaseAggregateWip 신설(M20_DAILY_LOT_RELEASE 기준 tick당 소수부 이월 계산)로 완료분만큼 지속 재투입하도록 수정",
    "관제탑 이자재·최생산·박물류 3인을 LLM_ONLY→RULE_LLM으로 전환 — 김구매 패턴을 그대로 복제해 materials-agent.ts·production-agent.ts·logistics-agent.ts 신설, 스냅샷에 역할별 규칙 필드 추가, AgentCard 판정 블록을 4역할 공용으로 일반화하고 근거 칩·역할별 딥링크(재고·작업지시·창고 화면) 추가",
    "4인 전원 판단 시 관제 결론 생성이 OPENAI_STRUCTURED_OUTPUT_EMPTY로 반복 실패하던 버그 규명 — 모델이 evidenceRefs에 근거 코드 대신 문장을 통째로 채워 토큰 예산을 소진하는 게 원인이었음. 프롬프트에 근거 코드 형식 명시·토큰 상한 상향·스키마 문자열 길이 제한으로 해결",
    "AI 판단 수동 ON/OFF 스위치 추가(월 예산 가드와 별개 즉시 차단) — OFF여도 각 역할 규칙엔진 판정을 LLM 비용 없이 즉시 기록해 감사로그가 끊기지 않도록 구현, 과거 판단 이력도 화면에서 사라지지 않게 유지",
    "WIP 처리량 병목 규명 — tick 간격과 진행 간격이 같아 만재고 상태에서 전체 14,040개가 동시에 진행 대상(due)이 되는데 처리 상한(2,000)에 막혀 86%가 매 tick 밀리며 route의 반복 구간(cell-array, 140스텝 중 88스텝)에 뭉쳐버리던 버그 발견 — 처리 상한을 목표재고+여유로 상향, FIFO 정렬 추가",
    "위 수정이 유발한 부작용 규명 및 근본 수정 — 동기화된 로트 무리가 매 tick 함께 자재를 태우고 발주를 유발해 창고 최대 654%까지 폭증, avgDailyBurn 지수이동평균에 상한이 없어 burst 한 번으로 200배까지 폭주하던 게 핵심 원인이었음. 로트 진행에 확률적 지연(15%)을 걸어 동기화된 무리를 서서히 분산시키고, EMA에 이전값 3배 클리핑을 적용해 한 tick의 극단치가 발주량을 폭주시키지 못하도록 이중 수정",
    "입고 관제 화면의 React key 중복 경고 규명·수정 — scenario-engine이 재고부족 자재의 classification과 warnings[].code에 EXISTING_SHORTAGE를 동시에 채워 reasonCodes 배열에 중복이 들어가던 기존 버그, buildProcurementShadow에서 dedup 처리",
    "전 과정 TDD로 회귀 테스트 8건 신규 추가(materials/production/logistics-agent, twin-wip-release, advance-aggregate-batch-cap, lot-desync, procurement-agent 중복방지, twin-inbound EMA 클리핑) 및 TypeScript·ESLint 클린 확인",
  ] },
  { day: 19, date: "2026-08-03", label: "역할별 운영 실행 + M21·M22 생산 진행", color: "#0F766E", items: [
    "레거시 Twin 엔진을 PAUSED로 유지하고 시작 API에 관리자 인증·역할 자동화 준비도 게이트를 추가 — DB 상태가 RUNNING이어도 역할 분리가 완료되지 않으면 tick을 건너뛰는 fail-closed 구조로 전환하고 M20 중앙 자동 오케스트레이션은 차단",
    "활성 Lot 전체 조회 API에서 조회만으로 Lot이 생성·진행되던 부작용을 제거해 순수 조회로 변경하고, 운영 책임을 김구매=발주·이자재=자재/재고·최생산=생산/WIP·박물류=이송/실물입고로 명문화",
    "입고 첫 역할 실행 수직 흐름 구축 — 확정 inbound plan의 ETA를 기준으로 박물류 실물확인 태스크를 만들고, 박물류 확인 후 이자재 정합화가 Lot·재고이동·Projection·입고계획을 하나의 거래로 갱신하도록 분리",
    "부분입고 후 잔량 태스크 재생성, request hash·버전 CAS·멱등키를 적용하고 WMS 역할 카드와 담당자 대화형 감사로그를 연결 — 계획 연계 Lot을 일반 입고 API로 우회 등록하는 경로도 차단",
    "3FAB 노드 밀도 화면을 M20 15노드·140단계, M21 6노드·120단계, M22 11노드·256단계로 확장하고 M22 공정군 색상·Fab별 라우트 위치 분포를 반영",
    "M21·M22 생산 진행을 최생산 전용 실행기로 연결 — 개별 FOUP 4만여 개를 허위 생성하지 않고 376개 Route-step 집계 버킷(M21 120개/19,626 FOUP-eq, M22 256개/21,600 FOUP-eq)으로 WIP 보존과 단계 이동을 기록",
    "15초 스캔·64배 모델 속도, 분산 락·시간창별 멱등 run·버킷 낙관적 버전·Route 불일치 HOLD·tick 집계 감사를 적용하고 실제 DB에서 bootstrap 및 2회 tick의 이동·완료·재투입과 총량 보존을 검증",
    "노드 밀도 카드에 최생산 RUNNING과 LIVE/STALE 심박, 최근 이동량·완료량·마지막 tick을 노출해 스케줄러가 멈췄을 때도 LIVE로 오인하지 않도록 개선",
    "운영 DB에서 레거시 Twin의 PAUSED·lastTickAt 불변을 확인하고 생산 모델 테스트·TypeScript·ESLint·diff 검사까지 완료",
  ] },
  { day: 20, date: "2026-08-08", label: "4-에이전트 실행권 이양 + 레거시 대정리 + 완제품 재고", color: "#B91C1C", items: [
    "김구매·박물류·이자재+최생산 3개 역할에 실행 게이팅을 순차 구현 — 김구매는 위험물·단일소싱 자재를 PENDING_APPROVAL로 분리(P0 발주량 스파이크 클립 포함), 박물류는 창고 CAPACITY_OVER 시 도착 화물을 INBOUND_HOLD로 보류, 이자재+최생산은 advanceAggregateWip 한 지점에서 COVERAGE_CRITICAL 자재를 쓰는 로트의 다음 스텝 진행을 자재차단으로 통합 게이팅(TDD 전 구간 검증)",
    "역할별 Executor·감사 추적이 갖춰졌다고 판단해 재가동 봉인(isRoleAutomationReady)을 사용자 승인으로 해제 — Twin과 레거시 M20_PILOT 오케스트레이터 양쪽이 걸려있던 단일 플래그였음을 확인하고 블라스트 반경을 설명한 뒤 함께 해제",
    "레거시 대정리 — /mes·orchestrateM20Agents(M20_PILOT) 체인, /wms·/inventory/verification 등 LOT/HU 단위 레거시 원장 화면, agent-meetings·/api/sim/* 죽은 코드를 전부 제거하고 InboundHoldPanel은 /warehouse로, InboundReceiptRolePanel은 /erp-bridge로 이전 — 홈(Campus Control Tower)과 관제탑 라이브를 한 페이지로 통합",
    "avgDailyBurn EMA 폭주 근본 원인 규명 — prevEma가 0(리셋 직후) 상태에서는 클리핑이 아예 적용 안 돼, Twin이 며칠 멈췄다 재개될 때 몰린 완료 burst가 그대로 새 기준선이 되고 거기서 다시 3배씩 불어나 설계기준 대비 최대 41배까지 벌어짐(CSM-001 173/일 vs 실측 7,083/일) — updateBurnEma에 설계기준 수요 기반 referenceCeiling을 추가해 부트스트랩·정상상태 양쪽 모두 상한 적용",
    "창고 용량 폭주가 3회 반복된 원인을 매번 다르게 오진단했다가(창고가 작다→재고를 깎음→신호가 안 고쳐져 재발) 최종적으로 avgDailyBurn 오염이 근본 원인임을 확인 — 오염값 리셋+설계기준 재트리밍 후 8개 원자재 창고 전부 6~27%대로 안정화, 창고 capacity 자체는 실측 전 계획값이라 손대지 않음",
    "완제품(M20 HBM) aggregate 재고 신설 — WaferLot 1개≠완제품 1개(다이싱→KGD→스택 팬아웃)라 원자재와 동일한 aggregate 수량 모델로 설계, fab-scenario.ts의 기존 완제품 환산 가정을 재사용해 웨이퍼 완료량을 스택 수로 환산, 완제품 창고(WH-FG01)를 기존 8개 창고와 같은 getWarehouseCapacity()에 통합(2D 상세로 분기)",
    "업계 관행(최종테스트 통과 전엔 판매재고 아님)을 반영해 패키징 완료→테스트대기 배치→시간 지연 후 재고 반영 큐를 추가(새 수율 없이 시간 게이트만) — 완제품 창고도 박물류 CAPACITY_OVER 게이팅 대상에 포함해 마지막 스텝 완료를 자재차단과 같은 방식으로 보류 가능하게 함",
    "가상 고객사 5곳과 월 계약물량(설계기준 월산출 기반)·이행률 표시, 수동 출하 처리 액션을 완제품 재고 화면에 추가 — 실제 영업 데이터가 없는 부분은 명시적으로 가상 라벨링",
    "김구매 자율등급 과잉분류 규명 — GAS/CHM 카테고리 전체를 위험물로 뭉뚱그려 44종 중 41종이 승인대기로 정체되던 문제를 supplyMode(BULK_GAS·BULK_CHEMICAL은 밴더관리 자동보충, SPECIALTY_CYLINDER만 진짜 위험물)로 정밀화 — 실측 결과 병목의 진짜 원인은 위험물 분류가 아니라 공급사 마스터의 단일소싱 데이터였음을 확인",
    "사용자 결정으로 김구매 승인 게이트를 완전자동화 — 위험물·단일소싱 분류와 사유는 계속 PO에 기록해 투명성을 유지하되 더 이상 사람의 승인 클릭 없이 실행, 기존 대기 39건도 같은 정책으로 일괄 전환(감사기록 보존)",
    "관제탑 최생산 판단이 폐기된 레거시 workOrders(M20_PILOT, /mes 제거 후 2026-07-27부터 정지)를 보고 있어 로트 12,590개가 실시간 자재차단 중인데도 화면엔 죽은 데이터만 뜨던 문제 발견 — advanceAggregateWip이 실제로 쓰는 waferLots 집계(자재차단·완제품창고차단)로 직접 판단하도록 재배선(TDD 검증)",
    "승인 방치 문제 대응으로 방치시간 기반 에스컬레이션(15분 주의·60분 긴급) UI를 관제탑·코크핏에 우선 추가했다가, 근본 결정(승인 자동화)이 나온 뒤에도 인프라는 남겨 재도입 가능하게 유지",
  ] },
  { day: 21, date: "2026-08-09", label: "완제품 재고 3제품 확장 — Step-Bucket 엔진", color: "#9333EA", items: [
    "Twin 엔진을 HBM 전용에서 DRAM(M21)·NAND(M22) 포함 3제품 루프로 일반화 — fab-production-config.ts 신설로 제품별 생산 config(wipMode, 원단위, 목표 WIP)를 단일 진실원으로 통합, M20 런타임은 기존 상수를 그대로 반환해 회귀 없이 보존",
    "DRAM·NAND는 17,173~18,720대 규모의 WIP를 매 틱 개별 FOUP 원장으로 진행하면 원격 DB에 틱당 5만 건 write가 나 응답이 7분까지 걸리던 문제를 step-bucket.ts(스텝별 수량 집계, wipStepBuckets 컬렉션) 도입으로 해결 — HBM은 기존 per-lot(waferLots) 유지",
    "자재 소모 계산도 3제품 루프에 연결해 DRAM·NAND가 실제로 원단위만큼 공유 재고를 태우게 하고, 완제품 API를 3제품 배열로, 신규 소모-산출 영수증 API(material-balance)를 추가",
    "FinishedGoodsClient를 3제품 스트립 + native/Gb 단위 토글 + 실시간 영수증 피드로 재구성",
    "실 DB 검증 — HBM 25.1M STACK·DRAM 7.98M CHIP·NAND 6.56M DIE 적립과 Gb 환산(DRAM 128Pb·NAND 6.72Eb) 확인, TypeScript 0 에러, 콘솔 에러 0",
    "후속 과제로 완제품 창고 혼합단위 용량(WH-FG01 하나가 STACK+CHIP+DIE를 그대로 합산)과 DRAM·NAND 출하 미지원을 기록 — 다음 세션에서 바로 터짐",
  ] },
  { day: 22, date: "2026-08-10", label: "문서 정합화 + 4-에이전트 실행·관측 간극 해소 + Twin 성능", color: "#EA580C", items: [
    "docs/ 전수 점검 — 삭제된 M20 파일럿 실행계층(orchestrateM20Agents 등)을 LIVE로 서술하던 agents/{mes,wms,process}-master.md에 ARCHIVED 배너 추가, vision·fab-master·route-master·warehouse-capacity-master 등 현재 코드와 어긋난 서술 정정, '신뢰 불가'류 불신 톤 대신 사실 위주 서술로 통일",
    "완제품 창고 단위 버그 발견·수정 — DRAM/NAND 확장 때 창고 마스터를 안 올려 3제품이 WH-FG01(HBM 기준 STACK 용량) 하나를 공유, getWarehouseCapacity가 STACK·CHIP·DIE를 단위 구분 없이 합산해 HBM 132일치 적체가 DRAM·NAND 생산까지 동반 정지시킴 — 제품별 창고(WH-FG01/02/03) 분리로 해결",
    "INBOUND_HOLD 영구 결품 수정 — 창고 CAPACITY_OVER로 보류된 PO를 settleArrivals가 재정산하지 않고 inTransit에는 계속 잡혀 재발주까지 막던 교착을 tick마다 재평가하도록 수정, 사람 수동해제와 동시 처리돼도 이중 입고가 안 나게 원자적 claim 적용",
    "김구매 발주 승인 게이트 복원 — PENDING_APPROVAL 승인 UI·API·decision-server는 이미 있었는데 engine.ts가 status를 항상 ORDERED로 하드코딩해 한 번도 작동한 적이 없었음을 발견해 연결 → 2026-08-08 '승인 클릭 요구 안 함' 사용자 결정과 정면 충돌한다는 걸 뒤늦게 파악 — 60분 SLA 타임아웃 자동승인으로 두 요구를 절충(사람이 먼저 볼 기회 + 방치돼도 영구히 안 막힘)",
    "관제탑 라이브 4에이전트 전수 점검 — 이자재·박물류·최생산(라이브 경로)은 이미 실제 상태 기반이었으나 김구매만 별도 온디맨드 그림자 시뮬레이션('자동모드였다면 ~했을 것')을 그대로 노출 중이었고, AI 스냅샷 경로(control-tower-snapshot-server.ts)는 최생산도 폐기된 workOrders를 참조 중이었음 — buildLiveProcurementShadow 신설로 김구매를 실제 twinPurchaseOrders 기반으로, 최생산도 두 경로 모두 라이브 신호로 통일",
    "avgDailyBurn EMA 자기강화 결품 나선 수정 — burnInventoryProjection이 반환한 burned(재고 부족 시 깎인 실차감량)만 EMA에 반영해 재고가 부족할수록 재발주가 더 안 나가던 구조를 진짜 요청 수요(burned+shortfall)로 교체(실측 결품률 08-05 40%→08-09 73% 악화 궤적과 일치)",
    "tick 겹침·N+1 쿼리 수정 — LOCK_TTL을 30초→300초로 올리고 스케줄러를 setInterval에서 self-scheduling setTimeout 체인으로 전환해 겹침을 구조적으로 차단, 자재마다 창고·재고·자재마스터를 최대 3중복 조회하던 걸(약 480쿼리/틱) 틱 시작 시 배치 조회 2건 + in-memory 스냅샷으로 교체 — 실측 tick 소요 95초→30초대로 단축",
    "DRAM·NAND 출하 경로 신설(옆 세션) — ShipmentDoc·API·출하 폼의 HBM 하드코딩 제거, 3제품 과잉재고 실측 정리(HBM 122%·DRAM 128%·NAND 142%→전부 70%)로 CAPACITY_OVER 차단 해소",
    "고객 계약 이행률 계산 버그 수정(옆 세션) — 이번 달 출하를 제품 구분 없이 합산·비교해 이행률이 820%까지 뜨던 걸 제품별 group으로 분리, 실측으로 HBM 201%(과다출하)·DRAM 10%·NAND 12%라는 실제 불균형이 드러남",
    "구조적 한계 확인 — 출하가 틱 자동이 아니라 사람·스크립트 트리거뿐이라 수동으로 비운 완제품 창고가 몇 시간 안에 다시 CAPACITY_OVER로 채워짐(NAND 70%→192%, 2시간) — 계약 라인 rate 기반 자동출하를 engine.ts 제품 루프에 추가하는 작업 착수",
  ] },
  { day: 23, date: "2026-08-11", label: "승인 게이트의 시간 단위 불일치 규명 — 라인 전면 정지 해소", color: "#0F766E", items: [
    "이상 신호 두 개('전구체 공급실 100% 초과', 'M20 WIP이 한 공정에 몰림')를 추적해 같은 뿌리임을 확인 — 승인 게이트의 시간 단위가 twin의 sim-time과 어긋나 있었다. PENDING_APPROVAL은 실벽시계 60분 SLA로 풀리는데 자재 소모는 가속돼서, 그 60분이 실측 약 103 sim일이었다(tick 26.2초 × 0.75 sim일/tick = 1.72 sim일/실분). 자재 ropDays는 7~45일이라 승인만 기다리다 ROP의 2~15배가 흘러 전 자재가 차례로 결품",
    "실측 피해 규모 — 자재 44종 중 19종 CRITICAL/STOCKOUT(13종 재고 0), M20 IN_PROGRESS 로트 14,040개 전부 materialBlockedAt으로 라인 완전 정지. 노드 밀도 화면의 '몰림'은 흐름이 아니라 정지 스냅샷이었다(route 스텝수 기대 cell-array 62.9%·beol-metal 17.9% → 실제 22.7%·67.0%로 역전, 로트가 P07 CMP·P03 세정 앞에 5스텝 주기로 정체)",
    "전구체 공급실도 같은 원인의 다른 얼굴 — 최다소모 TEOS(Si, 설계 467.5 L/일) 재고 0에 매 틱 shortfall인데, 소모가 1/30인 TEMAHf(15.8 L/일)가 방의 38%를 73일치로 점유. 게다가 현재 EMA 기준 목표재고(rop×2)를 다 채우면 약 1,457 슬롯이 필요한데 정원은 800 — 100% 초과가 정책상 보장된 상태",
    "사용자 결정으로 승인 게이트 제거 — initialPurchaseOrderStatus가 자율등급과 무관하게 항상 ORDERED를 반환하도록 바꿔 2026-08-08 정책('승인 클릭을 요구하지 않는다')으로 완전 복귀. 이 가속비에서는 사람이 실시간으로 승인을 누를 시간 자체가 없어 게이트를 두는 것이 곧 교착이다. autonomyCeiling 분류·사유는 계속 PO에 기록해 투명성 유지, SLA 타임아웃은 기존 대기분·수동 발주용 backstop으로 존치(TDD 검증)",
    "UPW-01 영구 CAPACITY_OVER 수정 — CONTINUOUS 모드 시설은 적치 개념이 없어 occupancy가 항상 100으로 고정되는데 warehouseVerdict가 그 값을 포화 임계값(>=100)에 그대로 넣어, 이 시설이 목적창고인 PO는 무조건 INBOUND_HOLD로 묶이고 박물류 카드도 늘 '수용 한계 초과'를 최상단에 띄우고 있었다. inventory-policy.ts의 capacityDecision이 이미 쓰던 규칙(현장 연속공급은 용량 판정 대상 아님)을 같이 적용 — 사용자가 먼저 버그라고 지적했는데 정상 동작으로 판단하고 넘어갔던 건",
    "ropDays < 리드타임 구조적 결품 수정 — ROP에 닿아 발주를 걸어도 남은 재고는 ropDays치인데 화물은 leadTimeDays 뒤에 도착하므로 그 차이만큼은 반드시 재고 0을 지나간다(CHM-002 과산화수소 ropDays 7일 vs CHM 리드타임 11일). ERP 쪽 calculateBaselineTarget이 이미 쓰던 protectedDays = max(ropDays, leadTimeDays)를 twin의 planInbound에도 적용해 두 계산을 일치시킴(TDD)",
    "창고 정원 산정 기준을 실제 재주문 정책에 맞춤 — resize-warehouse-capacity-to-demand가 ① 설계 수요를 M20 단독으로 잡고 있었고(08-09에 DRAM·NAND가 같은 재고를 공유하는 3제품 루프로 확장됐는데 sizing은 M20에 머물러 있었음) ② 기준을 ROP로 잡았는데 planInbound는 rop×2까지 채워서, 정책이 정상 작동하는 것만으로 정원의 2배가 들어오는 구조였다. 3제품 합 × max(ropDays, 리드타임) × rop×2 × 1.15로 재산정 — PRS-01 800→1,156(114%→79%), MWH-01 3,500→4,604",
    "정원 축소는 막았다(grow-only) — 설계 수요보다 재고가 많은 창고는 산정치가 현재 정원보다 작게 나오는데 그대로 줄이면 즉시 100%를 넘어 전 입고가 INBOUND_HOLD로 묶인다. '창고가 작다→재고를 깎음→재발'을 3회 반복한 게 정확히 이 실패였다(day 20). 과적재는 정원이 아니라 재고 쪽 문제로 분리해 경고만 남김(HZW-01·MRO-01)",
    "창고 유형별 점유 환산을 warehouseOccupancyFactor 한 곳으로 통합 — 런타임 점유율(getWarehouseCapacity)과 정원 산정이 서로 다른 환산을 쓰면 정원을 맞춰도 100%를 넘는다. 통합 전후로 MRO-01 산정치가 244→1,583으로 바뀐 게 그 간극의 크기",
    "완제품 창고 3곳이 0이 된 경위 규명 — 사람 출하가 아니라 08-10에 추가된 tick 자동출하(AGENT:정영업)였다. 계약 rate는 설계산출 기준으로 매 틱 고정으로 나가는데 라인은 자재 결품으로 설계의 2.5%밖에 못 만들고 있어서, tick당 출하 상한이 가용재고보다 항상 커 상한이 한 번도 안 걸리고 전량 출하됐다(최근 15분 3제품 모두 생산=출하 정확히 일치)",
    "발주 시점 창고 용량 인식 추가 — planInbound가 용량을 전혀 안 봐서 담을 수 없는 양을 주문해놓고 도착 시 INBOUND_HOLD로 묶이고, 보류 물량이 inTransit에 잡혀 재발주까지 막는 교착이었다. 목적창고 잔여 용량을 자재 수량으로 환산해 발주 상한으로 넘기고, 미도착 PO 점유분도 예산에서 차감(자재별 PO 조회 N+1도 같이 제거)",
    "COVERAGE_CRITICAL 자재 긴급 입고 예외 — 용량 보류(박물류)와 자재 차단(이자재+최생산)이 서로를 먹여 살리는 닫힌 루프였다. 창고가 안 빠져 자재가 못 들어오고, 자재가 없어 라인이 서고, 라인이 서니 창고가 안 빠짐. 라인 정지와 통로 적치 중 후자를 고른다는 판단으로 결품 임박 자재만 예외 처리 — 적용 후 INBOUND_HOLD 0건·초과 창고 0개",
    "4-에이전트 정책 정합성 감사 신설(scripts/audit-agent-policy-consistency.ts) — 규칙은 따로 보면 다 타당한데 같이 돌리면 라인이 서는 원인을 부등식으로 명시해 검사한다. 실측 위반 23건: R1 발주-차단 경합 17종(발주가 도착하기 전에 라인이 서도록 되어 있음), R2 정원-발주 경합 5개 창고(EMA 상한까지 오르면 정원의 106~261%), R4 출하-생산 경합 3제품(계약이 케파 90% 산출과 정확히 100% 일치해 완제품 여유가 0)",
    "docs/fab-operating-baseline.md 신설 — 케파 90% 운영을 기준선으로 잡고 각 에이전트 파라미터가 만족해야 할 부등식(R1~R4)을 정의. 시나리오를 기준선 대비 ±로 표현하고 그 편차에서도 부등식이 성립하는지 검사할 수 있게 했다. R3(기준선 운영 시 창고 점유 32~78%)가 통과하는 게 핵심 근거 — 정원이 부족한 게 아니라 EMA가 실수요를 3배로 과대평가하는 게 문제라는 뜻",
    "R1 해소 — 라인 차단을 STOCKOUT으로 한정(blockingMaterialIds 신설). 재고 862만 개·커버리지 13.5일인 PKG-LBD-001이 ropDays(30)×0.5=15일에 못 미친다고 전체 라인을 세우던 게 대표 사례로, 라인을 세우던 6종 중 4종이 재고 보유 상태였다. CRITICAL은 라인을 세우는 대신 긴급 조달(용량 초과여도 입고)을 발동시키는 신호로 역할을 분리해 두 규칙을 상보적으로 만듦 — R1 위반 17종 → 7종",
    "R2 해소 — BURN_EMA_CEILING_MULTIPLIER를 capacity.ts의 단일 상수로 옮겨 engine의 EMA 클리핑·창고 정원 산정·정합성 감사 세 곳이 같은 값을 읽게 했다(갈라지면 '정원은 설계 기준인데 발주는 EMA 기준'인 모순이 재발). 값은 3→1.5로 인하 — 가장 공격적인 증산 시나리오(EXPANSION)도 기준선 대비 1.22배라 안에 들어온다. 정원 재산정 후 EMA 상한 적재가 정원의 100% 이하로 들어와 R2 전 창고 통과",
    "R5 신설 — 발주가 정원을 정확히 100%까지 채우면 그 즉시 박물류의 CAPACITY_OVER 임계에 걸려 다음 입고가 전부 보류된다(정원을 꽉 채우는 것과 입고를 멈추는 것이 같은 지점). 실관측으로 MWH-01·MWH-02가 정확히 100%에서 고착하는 걸 확인하고 ORDER_CAPACITY_TARGET_RATIO=0.95 도입",
    "R4는 위반이 아니었음을 확인 — 감사 스크립트가 가동률을 두 번 곱한 계산 오류였다. fab-scenario의 waferStartsPerMonth가 이미 nominalWspm×utilization이라 설계 산출 자체가 케파 90% 기준선 값인데 거기에 0.9를 또 곱했다. 정정 후 계약은 기준선 산출의 90%로 여유 10% 확보 상태 — 완제품이 0으로 빨린 건 계약 과다가 아니라 라인이 설계의 2.5%만 생산한 탓이 맞다",
    "잔여 과제 — 남은 R1 위반 7종은 전부 CHM 계열로, 자재 마스터의 ropDays(7~10일)가 조달 리드타임(11일)보다 짧은 데이터 문제다. planInbound의 max() 보정으로 즉시 결품까지 가진 않지만 도착 여유가 정확히 0이라 수요가 흔들리면 결품난다. 코드에서 안전계수로 덮으면 마스터가 틀린 채 숨겨지므로 조달 승인을 받아 마스터를 정정하는 게 근본 처리. 그 외 완제품 목표 DOH 설정, HZW-01·MRO-01 과적재 재고 정리",
  ] },
  { day: 24, date: "2026-08-18", label: "리드타임 진실원 통일 — DOH 0일 자재 규명", color: "#B45309", items: [
    "재고 화면에 DOH가 0일에 붙은 자재 10종의 원인 규명 — 계산식(전체 현재고 ÷ 일평균사용량) 문제가 아니라 트윈 엔진이 132시간(5.5일) 전에 멈춰 있었다. 운영시계가 7.80일차에서 정지했는데 재보충 PO 23건의 도착 운영시각은 10.05~16.31일차라, 재고가 소진된 상태에서 입고만 얼어붙은 스냅샷을 보고 있던 것. 만료된 락은 acquireTwinLock이 자동 회수하므로 재기동 자체에는 장애가 없었다",
    "리드타임 진실원이 둘로 갈라져 있던 것을 통일(TDD) — 트윈 발주는 getBaseLeadTime(카테고리 평균: CHM 11·GAS 5·PKG 8·기타 7)을 쓰고 ERP 재고정책은 승인 주공급사 마스터를 써서 같은 자재의 리드타임이 두 값이었다. 실측 괴리: GAS-006 NF₃ 마스터 21일 vs 트윈 5일, CSM-016 Edge Trim Blade 45일 vs 7일, CHM-003 황산은 반대로 마스터 7일인데 트윈이 11일로 발주해 ropDays를 4일 초과. resolveLeadTimeDays를 신설해 공급사 선정 규칙(승인+주공급사 우선)을 buildProcurementSummary에 위임 — 트윈 엔진과 창고 정원 산정이 ERP와 문자 그대로 같은 함수로 같은 값을 고른다. 조달 마스터는 tick 배치 조회에 실어 N+1 재발 방지",
    "승인 주공급사 미등록 27종 해소 — 공급사 링크 자체가 없어 buildProcurementSummary가 null을 내고 재고정책이 BLOCKED_MASTER_DATA로 막혀 목표재고가 서지 않던 자재들. UTL-002 배기 스크러버액은 DOH 2.0일인데 발주가 한 건도 안 나가 있었다. 자재 성격에 맞는 실존 공급사(식각가스 SK가스·도판트 Air Products·전구체 MKS·습식케미컬 솔브레인 등)를 붙이고 리드타임은 카테고리 기준값으로 등록 — 트윈 동작을 바꾸지 않으면서 그 값을 마스터에 명시해 ERP가 같은 값을 보게 했다",
    "ropDays < 리드타임 구조적 결품을 마스터에서 정정 — 37종(day 23 잔여 과제). ROP에 닿아 발주해도 화물은 리드타임 뒤에 오므로 그 차이만큼 반드시 재고 0을 지나간다. 코드 안전계수로 덮으면 마스터가 틀린 채 숨겨지므로 correctedReorderPointDays로 ROP ≥ LT×1.3을 마스터에 반영(TDD). 탱크가 담을 수 있는 양을 넘겨 잡으면 BLOCKED_CAPACITY로 되돌아오므로 만재 일수의 95% 안으로 클램프하고, 클램프 결과가 현재 값보다 작으면 마스터를 후퇴시키지 않는다. ROP<LT 위반 10종 → 0종, 적용 전 값은 .backup/ropDays-*.json에 덤프",
    "점유 환산 통합의 미완 지점 수정 — day 23에 warehouseOccupancyFactor 한 곳으로 모았다고 했으나 calibrate-inventory-policy가 위험물·전구체·MRO 창고의 환산계수를 1로 하드코딩한 채 남아 있었다. 점유율(capacity.occupancy)은 환산값으로 오는데 재고 증분만 원단위로 더하니, 재고단위≠보관단위인 창고에서 점유가 과대평가돼 멀쩡한 자재가 막혔다. 수정 후 GAS-004 실란(법적 한도 3,987 초과)·GAS-014 TEOS(시설 한도 9,239 초과)가 둘 다 해소 — 창고 정원을 늘려야 할 실제 근거가 아니라 환산 불일치가 만든 가짜 초과였다",
    "재고정책 재산정 결과 ready=14 blockedCapacity=0 blockedMaster=0 (이전 ready=12 · capacity 2 · master 5)",
  ] },
  { day: 25, date: "2026-08-20", label: "운영 트렌드 대시보드와 24배속 정합성 수정", color: "#B45309", items: [
    "24배속 감사 — 운영시계를 쓰는 쪽(WIP·소모·발주 ETA·최종테스트·자동출하 실행)은 정합했다. 문제는 시계가 아니라 집계 창이었다. 계약 이행률은 벽시계 달력 월 창에 운영 24개월치를 모아 운영 1개월 계약으로 나눴고(실측 DRAM 6.5배·NAND 6.4배·HBM 3.8배 과대, 벽시계 월초마다 0으로 리셋되는 톱니), 공정별 사용량 실적은 30 벽시계일(= 운영 720일) 소모를 운영 1개월 설계치와 나란히 놓고 usageGap을 계산했다. 둘 다 운영시간 창으로 교체 — 24×가 맞게 도는 바로 그 이유 때문에 벽시계 창으로 세면 어긋난다",
    "화면이 배속을 1×로 표시하던 것 정정 — twinState.speedMultiplier는 운영시계가 읽지 않는 사문화 필드인데 M20 노드밀도 카드가 그 값을 배속으로 렌더했다. 필드를 코드와 DB에서 제거하고 OPERATING_SPEED_MULTIPLIER 표기로 교체",
    "tick 횟수 기반 시간 진행 제거 — RULES가 금지한 simDaysPerTick 패턴이 발주 승인 스크립트 3개(approve-all-pending-pos·approve-pkg-001-po·autonomize-pending-approvals)에 남아 ETA를 tickIntervalMs/simDays로 만들고 있었다. 감사 때는 하나만 잡혔는데 실제로는 셋이었다. 반면 test-twin-calibration의 operatingDaysPerStep은 위반이 아니라 정당한 도메인 계산(공정 스텝 1개가 운영시간 며칠인가)이라 옛 이름 메시지만 정정",
    "스케줄러 기동 취약점 수정 — register()가 두 동적 import를 모두 await한 뒤에야 startTwinScheduler를 불러서, 뒤쪽 import가 부팅 시 던지면 트윈 엔진이 조용히 안 떴다. 2026-08-12 22:35부터 132시간 tick 0회였던 사고의 유력한 경로다(그 날 22:38에 이 순서를 만든 편집이 있다). 각 스케줄러를 독립 기동하고 실패를 이름과 함께 로깅",
    "운영 트렌드 화면 신설(/trends) — 생산 실산출률·자재 결품과 커버리지·창고 점유율·계약 이행률 4축을 운영일 축에 그린다. 재고 커버리지와 창고 점유는 상태라 이벤트로 과거를 복원할 수 없어, 엔진 tick이 운영일 경계를 넘을 때 twinDailySnapshots에 하루치를 확정 적재한다(_id가 운영일이라 중복 적재 불가). 별도 스케줄러를 만들지 않은 건 RULES의 '기능별 독자 시계 금지' 때문이고, 운영시계를 이미 들고 있는 tick이 유일하게 옳은 위치다",
    "과거 백필은 하지 않는다 — 운영시계에 catch-up 상한이 있어 정지 공백이 잘리므로 벽↔운영 매핑이 구간별로 끊긴다(실측: 5.5 벽시계일 정지에 운영시각은 1일만 흐름). 과거 이벤트의 벽시계 tickAt에서 그 시점의 운영일을 되살릴 방법이 없다. 화면에 적재 시작일을 명시하는 쪽을 택했고, 표본이 1개일 때 빈 차트로 보이지 않도록 고립점을 점으로 찍는다",
    "엔진 정지가 그림에 드러나게 — 엔진이 멈추면 운영일이 안 넘어가 스냅샷도 안 생긴다. 벽시계 축으로 토글하면 그 구간이 공백 밴드로 보이고, 정책 변경 마커와 겹쳐 읽으면 '마스터를 고친 뒤 결품 곡선이 꺾였는가'가 한 화면에서 확인된다",
    "차트는 라이브러리 없이 인라인 SVG — 제품 계열 색(HBM #0078D4·DRAM #B5179E·NAND #0E9B8A)은 색약 검증 6항목 전부 통과(최악 인접쌍 deutan ΔE 9.8·정상시야 26.9). 상태색(#EA002C·#F7A600·#00B96B)은 예약이라 계열 색으로 쓰지 않고, 창고 8개는 categorical 한계를 넘어 스파크라인 small multiples로 나눴다",
    "잔여 과제 — twinDailySnapshots.policy(R1~R4 위반 건수)와 warehouses.baselineUtilization은 현재 0으로 적재된다. 판정 로직이 scripts/audit-agent-policy-consistency.ts에 있어 tick에서 부르려면 순수 부분을 src/lib로 옮겨야 한다. 마커는 값이 채워지면 즉시 동작하도록 만들어져 있다",
    "대시보드 시각 설계 정비 — 첫 구현이 회색 격자에 얇은 선뿐이라 휑했다. dataviz 마크 규격으로 다시 맞췄다: 영역 워시(계열 색 16%), 끝점 마커 r=4 + 2px 표면 링, 끝값만 직접 라벨, 컬럼 24px 상한에 데이터 끝만 4px 라운드, 격자·기준선은 hairline 실선(점선 금지), 큰 독립 숫자는 비례 숫자체. 형태가 틀린 것도 둘 고쳤다 — '막대 하나짜리 막대차트'는 안티패턴이라 히어로 + KPI 스탯 타일 4개로, 창고 8칸은 점 하나짜리 스파크라인 대신 미터(현재 점유 + 임계 눈금)로. k8s dashboard 설계문서에서 전이되는 원칙 반영(카드는 O(20)까지 유효 / 점진적 공개 — 창고 타일에서 상세로 드릴다운)",
    "엔진 상시 가동 경로 신설 — instrumentation의 setTimeout 체인은 살아있는 Node 프로세스를 전제해서 서버리스(Vercel)에서는 인스턴스와 함께 죽는다. 운영시계가 벽시계 경과 × 24로 흐르므로 호출 간격이 5초든 60초든 시간은 같은 속도로 간다(굵어지는 건 해상도뿐) — 이 성질 덕에 외부 cron이 때리는 /api/twin/tick으로 옮길 수 있었다. 실측: 인증 401·미설정 503, 락 점유 중 skipped=LOCKED로 동시 실행 없음, 락 해제 시 실제 tick 22.9초, 정상 tick 45.3초로 Vercel Pro 300초 안. vercel.json의 분 단위 cron은 Pro 전용",
    "결품이 며칠째 안 풀린 이유 규명 — 조달 루프는 처음부터 정상이었다(미착 PO 41건·최근 운영 10일 내 입고 26건·발주 누락 0종). 리드타임은 운영시간이라 21 운영일치 화물은 엔진이 실제로 21 운영일을 돌아야 도착하는데, catch-up 상한이 정지 구간을 버리기 때문에 꺼져 있던 시간은 만회되지 않는다. 개발하느라 서버를 하루에 여덟 번 재시작하는 동안 팹은 연속 가동 시간을 얻지 못했다 — 자재 정책 문제가 아니었다",
    "발주가 벌크 탱크의 물리 한도를 보지 않던 것 수정 — 엔진이 capacityHeadroomQty를 SPACE 창고에만 계산해 넘겨서(capacityMode !== 'SPACE'면 continue) 탱크 자재는 용량 제약을 아예 안 봤다. planInbound는 rop×2를 주문하는데 그 양이 탱크보다 큰 자재가 12종이었다(탱크의 1.1~1.5배). 탱크를 키울 필요는 없었다 — 12종 전부 capDays > ropDays > leadTime이라 ROP 수위를 담고 리드타임도 커버한다. 발주가 용기를 안 본 것뿐이라 잔여 = 한도 − (현재고 + 미착)까지만 주문하게 했다(TDD)",
    "콜드스타트 리셋 스크립트 신설과 그 한계 — 결품 15종을 설계 목표치로 채워 라인을 즉시 재개시켰다. 첫 시도는 ROP 수위로 채웠는데 그건 재주문 트리거지 정책 유지수위가 아니라(planInbound는 rop×2까지 채운다) 40분 만에 4종이 재결품났다. 목표를 rop×2로 올리고 탱크 한도로 클램프해 다시 적용",
    "그럼에도 결품이 재발했다 — 리필 후 운영 1일(실제 1시간) 만에 13종이 다시 0. CHM-004 기준 탱크 한도 4,618을 채웠는데 하루 만에 약 4,000을 소모했다(설계 일소요 314의 12배 이상). 리필 직전 막힌 로트가 49,065개였으므로 라인이 풀리며 생긴 catch-up burst로 추정하나 **아직 검증하지 않았다**. 리필은 두 번으로 멈춘다 — 세 번째는 day 20이 기록한 '창고가 작다→재고를 깎음→재발' 3회 반복과 같은 증상 덮기가 된다. 다음에 볼 곳은 소모가 왜 설계의 12배인가 한 곳(advanceBatchMax·BURN_EMA_CEILING_MULTIPLIER)",
  ] },
];

export default function DevlogPage() {
  return <>
    <div className="mb-1 text-2xl font-extrabold tracking-tight">개발 이력</div>
    <div className="mb-8 text-sm text-[#999]">FAB 자재관리 시스템 · 세션별 구현 및 운영 규칙 변경 기록</div>
    <div className="relative">
      <div className="absolute bottom-0 left-[17px] top-0 w-px bg-[#E8E8E8]" />
      <div className="space-y-5">{[...LOGS].reverse().map((log) => <article key={log.day} className="relative flex gap-5">
        <div className="z-10 flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-xs font-black text-white shadow-sm" style={{ backgroundColor: log.color }}>D{log.day}</div>
        <div className="flex-1 overflow-hidden rounded-2xl border bg-white shadow-sm">
          <div className="flex items-center gap-3 border-b px-5 py-3"><span className="rounded-full px-2.5 py-0.5 text-xs font-black text-white" style={{ backgroundColor: log.color }}>Day {log.day}</span><h2 className="text-sm font-bold">{log.label}</h2><time className="ml-auto font-mono text-[11px] text-[#999]">{log.date}</time></div>
          <ul className="space-y-2 px-5 py-4">{log.items.map((item) => <li key={item} className="flex items-start gap-2 text-[13px] text-[#333]"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full" style={{ backgroundColor: log.color }} />{item}</li>)}</ul>
        </div>
      </article>)}</div>
    </div>
  </>;
}
